version: '3.1'

services:
  mongo:
    image: mongo:4.4.8
    container_name: "belorder-test-mongo"
    restart: always
    volumes:
      - ./.data/mongo:/data/db
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_DATABASE: belordertest
      MONGO_INITDB_ROOT_USERNAME: belordertest
      MONGO_INITDB_ROOT_PASSWORD: password
